
#En este código, la función `read_config_file()` lee las variables de la aplicacion para
# las configuraciones desde el archivo `config.ini`, que tiene el siguiente formato:

# Variable fecha cuantos dias futuro se consulta
  #  tener en cuenta que los dias domingos no consulta hace la consulta para el dia sigiente
  #  EJEMPLO: 0 HOY, 1 dia sigiente 2 dos dias despues ...
[SERVICIO]
dias = 1
usuario= ClaudiaForero

# el tiempo que se demora para enviar el siguiente mensaje
[MENSAJES]
	# el tiempo es en segundos
mensagetime = 8

# Variables dela programacion de la tarea
[SCHEDULE]
# cada cuanto valida el scheduler
	# el tiempo es en segundos
sleeptme = 60
# cuando se programa por un rango de hora en unos minuto especifico
byrange = False
start_hour = 10
end_hour = 11
minute = [30]
	# cuando usa archivo con lista de horas especifico
byHour = True
archivohorario = ./config/horas_ejecucion.txt
# Dias que no ejecuta el proceso de envio 
	# El 6 representa el domingo (lunes es 0, martes es 1, y así sucesivamente)
exepDias = [6] 


#Variables de configuracion del Log
[LOGG]
LogFile = ./log/EnvioMail
LogLevel = INFO   

[API]
UrlApi = http://localhost:8000/calendar/list/
UrlApiWapp = http://localhost:3002/lead

# Variable del SQL que ejecuta para el mensaje que envia
[QUERY]
sql = select  
		a.id as id,
		'57'||a.description_telefono as telefono,
		F_DIAS_TARDES_NOCHEs(now()::timestamp::time)||'.||'||
		' Le escribo para confirmar la cita de ' ||a.description_nombre ||
		' programada para el dia '||a.start_date_fecha||' a las **'||a.start_date_hora||
		'** con la doctora '||u.nombreusuario ||'.|| ||'||
		'Direccion: '||u.direccion||'.|| ||'||
		'Por favor confirmar asistencia para poder dar oportunidad a otro paciente, en caso de no poder asistir.|| ||'||
		'Para cancelar la cita ingrese al link: ||'||a.htmllink 
		as mensaje
		from agenda_google a
        join datos_usuario u on (u.id_usuario = a.id_usuario)
		where a.mail_enviado = false
		and a.start_date_fecha = :fecha
		and a.id_usuario = :usuario
		order by start_date